import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer, Header, ProductCard } from "../components";
import { AccountForm, ContactForm, TrackOrderForm } from "../contact-form";
import { products } from "../data";

type PageKey = keyof typeof pageMeta;
const pageMeta = {
  about: ["Our Story", "Meet AMB BOUTIQUE, a contemporary women’s fashion boutique curated in San Diego by founder Ana Paula Maciel."],
  contact: ["Contact Us", "Contact AMB BOUTIQUE for product, order, shipping, return or partnership support."],
  faq: ["Frequently Asked Questions", "Answers about AMB BOUTIQUE orders, sizing, shipping, returns and international shopping."],
  shipping: ["Shipping", "AMB BOUTIQUE processing, delivery, international shipping, duties and tracking information."],
  returns: ["Returns & Exchanges", "How to request an eligible AMB BOUTIQUE return within 30 days."],
  privacy: ["Privacy Policy", "How AMB BOUTIQUE collects, uses, shares and protects personal information."],
  terms: ["Terms of Service", "Terms governing use of the AMB BOUTIQUE website and online store."],
  cookies: ["Cookie Policy", "How AMB BOUTIQUE uses essential and optional cookies and similar technologies."],
  accessibility: ["Accessibility", "AMB BOUTIQUE’s commitment to an inclusive online shopping experience."],
  "size-guide": ["Size Guide", "Women’s international size conversion for the US, Canada, UK, Australia and New Zealand."],
  "track-order": ["Track Your Order", "Check the status of an AMB BOUTIQUE order."],
  account: ["Your Account", "Access AMB BOUTIQUE orders, saved details and account preferences."],
  sale: ["Sale", "Shop women’s dresses, tops, playsuits, bags and shoes on sale at AMB BOUTIQUE."],
} as const;

export function generateStaticParams() { return Object.keys(pageMeta).map((page) => ({ page })); }

export async function generateMetadata({ params }: { params: Promise<{ page: string }> }): Promise<Metadata> {
  const { page } = await params;
  if (!(page in pageMeta)) return {};
  const [title, description] = pageMeta[page as PageKey];
  return { title, description, alternates: { canonical: `/${page}` }, openGraph: { title, description, url: `/${page}` } };
}

export default async function StandardPage({ params }: { params: Promise<{ page: string }> }) {
  const { page } = await params;
  if (!(page in pageMeta)) notFound();
  const key = page as PageKey;
  const [title, description] = pageMeta[key];
  if (key === "sale") return <main><Header/><section className="info-hero sale-hero"><p>THE AMB EDIT</p><h1>Sale</h1><span>Considered pieces, special prices.</span></section><section className="section shell"><div className="product-grid">{products.filter((product) => product.compareAt).map((product) => <ProductCard product={product} key={product.slug}/>)}</div></section><Footer/></main>;

  return <main><Header/><section className="info-hero"><p>AMB BOUTIQUE · SAN DIEGO</p><h1>{title}</h1><span>{description}</span></section><article className={`info-content shell info-${key}`}>{content[key]}</article><Footer/></main>;
}

const effectiveDate = <p className="policy-date">Effective August 8, 2026 · Last updated August 10, 2026</p>;

const content: Record<Exclude<PageKey, "sale">, React.ReactNode> = {
  about: <><div className="about-lead"><div className="about-image"/><div><p className="eyebrow">FOUNDED BY ANA PAULA MACIEL</p><h2>California ease, thoughtfully curated.</h2><p>AMB BOUTIQUE began with a clear point of view: getting dressed should feel effortless, polished and personal. From San Diego, founder Ana Paula Maciel curates feminine silhouettes, versatile separates, statement bags and finishing-touch shoes for days that move from coffee to dinner.</p><p>Our edit is created for women in the United States, Canada, the United Kingdom, Australia and New Zealand, with clear sizing, honest product details and service that feels human.</p><Link className="button dark" href="/collections">Explore the Edit</Link></div></div><section className="values-copy"><div><strong>Considered style</strong><p>Pieces selected for versatility, confidence and repeat wear.</p></div><div><strong>San Diego spirit</strong><p>Warm, modern and relaxed without losing its polish.</p></div><div><strong>Personal service</strong><p>Questions are answered by a real team at info@ambboutique.online.</p></div></section></>,
  contact: <div className="two-column-info"><div><h2>We’re here to help.</h2><p>For product guidance, sizing questions, order support, returns, press or partnerships, send us a note. We aim to reply within two business days.</p><address>AMB BOUTIQUE<br/>Owner &amp; operator: Ana Paula Maciel<br/>San Diego, California, United States<br/><a href="mailto:info@ambboutique.online">info@ambboutique.online</a></address><p>Support hours: Monday–Friday, 9:00 a.m.–5:00 p.m. Pacific Time, excluding U.S. holidays.</p></div><ContactForm/></div>,
  faq: <div className="faq-list"><details open><summary>Where is AMB BOUTIQUE based?</summary><p>We are based in San Diego, California, and serve customers in the United States, Canada, the United Kingdom, Australia and New Zealand.</p></details><details><summary>Which sizes do you carry?</summary><p>Available sizes appear on each product page. Product-specific measurements and international conversions are provided where relevant.</p></details><details><summary>When will my order ship?</summary><p>In-stock orders are normally processed within 1–3 business days. Pre-order timing will be clearly shown on the product page when applicable.</p></details><details><summary>Do you ship internationally?</summary><p>Yes. We ship to Canada, the United Kingdom, Australia and New Zealand. Final shipping charges are shown at checkout. International customers are responsible for import duties, taxes and brokerage fees unless checkout expressly says they are included.</p></details><details><summary>What is your return window?</summary><p>You may request a return within 30 days after delivery, subject to the conditions in our <Link href="/returns">Returns Policy</Link>.</p></details><details><summary>How do I contact you?</summary><p>Email <a href="mailto:info@ambboutique.online">info@ambboutique.online</a> or use our <Link href="/contact">contact form</Link>.</p></details></div>,
  shipping: <>{effectiveDate}<h2>Order processing</h2><p>In-stock orders are normally prepared within 1–3 business days, excluding weekends and U.S. holidays. During launches or high-volume periods, processing may take longer. Pre-order and made-to-order timing will be disclosed on the relevant product page when applicable.</p><h2>Delivery estimates</h2><div className="policy-table"><div><strong>United States</strong><span>Approximately 3–7 business days after dispatch</span></div><div><strong>Canada</strong><span>Approximately 7–15 business days after dispatch</span></div><div><strong>United Kingdom</strong><span>Approximately 7–15 business days after dispatch</span></div><div><strong>Australia & New Zealand</strong><span>Approximately 10–21 business days after dispatch</span></div></div><p>These are estimates, not guarantees. Customs, weather and carrier delays are outside our control.</p><h2>Rates, duties and taxes</h2><p>Available services and final shipping charges are shown at checkout. U.S. merchandise orders of $99 or more qualify for complimentary standard domestic shipping unless an exclusion is stated. International delivery is charged separately based on destination and packed weight. International orders do not qualify for complimentary shipping unless checkout expressly states otherwise. International customers are responsible for import duties, taxes and brokerage fees unless checkout expressly says they are included.</p><h2>Tracking and address changes</h2><p>When an order ships, we will send tracking to the email used at checkout. Contact us immediately if the address is wrong; we cannot guarantee changes after fulfilment begins.</p><h2>Lost or damaged parcels</h2><p>Contact <a href="mailto:info@ambboutique.online">info@ambboutique.online</a> within seven days of a damaged delivery. For a parcel marked delivered but not received, check with household members and the carrier before contacting us.</p></>,
  returns: <>{effectiveDate}<h2>30-day return requests</h2><p>You may request a return within 30 days after delivery. Items must be unworn, unwashed, unaltered, free from fragrance or marks, and returned with original tags and packaging. A return must be authorized before it is sent.</p><h2>Non-returnable items</h2><ul><li>Final sale items and gift cards</li><li>Personal-care or hygiene-sensitive items where the seal has been opened</li><li>Items showing wear, washing, alteration, scent, makeup or damage after delivery</li></ul><h2>How to request a return</h2><ol><li>Email <a href="mailto:info@ambboutique.online">info@ambboutique.online</a> with your order number and reason.</li><li>Wait for authorization and the correct return address.</li><li>Pack the item securely and retain proof of postage.</li></ol><p>Do not send returns to an unconfirmed address. Unless the item arrived defective or incorrect, original delivery charges and return postage are not refundable.</p><h2>Refunds and exchanges</h2><p>Approved refunds are issued to the original payment method after inspection. Bank processing time varies. Exchanges depend on inventory; the fastest option may be to return the original item and place a new order.</p><h2>Your statutory rights</h2><p>Nothing in this policy limits consumer rights that cannot legally be excluded in your country or state.</p></>,
  privacy: <>{effectiveDate}<p>AMB BOUTIQUE, operated by Ana Paula Maciel in San Diego, California, is responsible for the personal information described in this policy. Questions and privacy requests may be sent to <a href="mailto:info@ambboutique.online">info@ambboutique.online</a>.</p><h2>Information we collect</h2><ul><li>Contact and identity details, such as name, email, phone and shipping or billing address.</li><li>Order, payment and transaction details. Full payment-card numbers are handled by our payment provider and are not stored by us.</li><li>Account, customer-service, return, survey and marketing preferences.</li><li>Device, browser, IP address, approximate location, cookie and website-usage information.</li></ul><h2>How we use information</h2><p>We use information to provide the store, process and deliver orders, prevent fraud, communicate with you, manage returns, comply with law, improve our services and—where permitted or consented—send marketing.</p><h2>How we disclose information</h2><p>We disclose only what is reasonably needed to providers supporting payments, hosting, email, analytics, fraud prevention, fulfilment, shipping and professional advice; to authorities when required; or in a legitimate business transfer. We do not sell personal information for money. We do not share it for cross-context behavioural advertising unless we first provide the choices required by applicable law.</p><h2>International processing and retention</h2><p>Because we serve several countries, information may be processed in the United States and other locations where our providers operate. We use appropriate contractual or legal safeguards when required. We retain information only as long as necessary for the purposes above, legal obligations, disputes and security.</p><h2>Your privacy choices</h2><p>Depending on where you live, you may have rights to access, correct, delete, restrict or object to processing, receive a portable copy, withdraw consent, opt out of certain sharing, or appeal a decision. California residents may also request categories or specific pieces of information and receive equal service after exercising rights. UK residents may complain to the ICO; Canadian, Australian and New Zealand residents may contact their local privacy regulator.</p><p>To exercise a right, email us with “Privacy Request” in the subject. We may verify identity before responding. You can unsubscribe from marketing through any marketing email.</p><h2>Children and security</h2><p>Our store is not directed to children under 13, and we do not knowingly collect their personal information. We use reasonable administrative, technical and organisational safeguards, but no online system is completely secure.</p><h2>Changes</h2><p>We may update this policy and will post the revised date here. Material changes will be communicated where required.</p></>,
  terms: <>{effectiveDate}<p>These Terms govern your use of ambboutique.online and purchases from AMB BOUTIQUE, operated by Ana Paula Maciel in San Diego, California. By using the site, you agree to them.</p><h2>Store information and eligibility</h2><p>You must provide accurate information and be legally able to enter a contract. Product colours and appearance may vary by screen. Measurements and materials on each product page form part of the product description.</p><h2>Prices, orders and payment</h2><p>Prices appear in the selected currency where supported. Taxes, shipping and duties may be added at checkout. An order confirmation acknowledges receipt; it does not guarantee acceptance. We may cancel or limit an order for inventory errors, suspected fraud, pricing mistakes or legal restrictions and will refund amounts charged for cancelled items.</p><h2>Shipping, returns and promotions</h2><p>Our <Link href="/shipping">Shipping Policy</Link> and <Link href="/returns">Returns Policy</Link> form part of these Terms. Promotions may have separate conditions and may not be combined unless stated.</p><h2>Intellectual property and acceptable use</h2><p>The AMB BOUTIQUE name, site design, text, graphics and original content are protected by applicable intellectual-property laws. You may use the site for personal shopping only and may not interfere with security, scrape the store at unreasonable volume or reuse content commercially without permission.</p><h2>Third-party services and disclaimers</h2><p>Payment, delivery and other services may be provided by third parties under their own terms. To the maximum extent allowed by law, the site is provided without guarantees beyond those expressly stated and mandatory consumer rights.</p><h2>Liability and governing law</h2><p>To the maximum extent permitted by law, AMB BOUTIQUE is not liable for indirect or consequential loss. These Terms are governed by California law, without removing mandatory protections available to consumers where they live.</p><h2>Contact</h2><p>Questions: <a href="mailto:info@ambboutique.online">info@ambboutique.online</a>.</p></>,
  cookies: <>{effectiveDate}<h2>What cookies are</h2><p>Cookies and similar technologies store or read information on your browser or device. Some are required for shopping-bag, checkout, security, language and privacy-preference functions.</p><h2>Our categories</h2><div className="policy-table"><div><strong>Essential</strong><span>Required for the site, security, cart and consent preferences; cannot be switched off through our banner.</span></div><div><strong>Analytics</strong><span>Help us understand site performance and use. They remain off unless you consent where consent is required.</span></div><div><strong>Marketing</strong><span>May measure campaigns or personalise advertising. They remain off unless you consent where consent is required.</span></div></div><h2>Your choices</h2><p>You may accept all or continue with essential technologies only through our banner. You can also clear the saved preference in your browser to see the choices again. Browser settings can block cookies, but doing so may prevent cart or checkout functions.</p><h2>Service providers and updates</h2><p>Optional analytics and marketing technologies remain off unless the applicable consent has been given. When an optional provider is enabled, its purpose is disclosed through this policy or the consent interface.</p><p>Questions: <a href="mailto:info@ambboutique.online">info@ambboutique.online</a>.</p></>,
  accessibility: <>{effectiveDate}<h2>Our commitment</h2><p>AMB BOUTIQUE wants everyone to shop with dignity and independence. We are designing the site toward WCAG 2.2 Level AA, including keyboard access, meaningful headings, form labels, visible focus states, text alternatives and sufficient contrast.</p><h2>Need assistance?</h2><p>If any part of the site creates a barrier, email <a href="mailto:info@ambboutique.online">info@ambboutique.online</a>. Tell us the page, the issue, your browser or assistive technology if comfortable, and the format or accommodation you need. We aim to acknowledge accessibility messages within two business days.</p><h2>Ongoing work</h2><p>Accessibility is an ongoing practice. We test key shopping journeys and review issues when features, images and product content change. Third-party services may have separate accessibility limitations; we will work with providers and offer a reasonable alternative where possible.</p></>,
  "size-guide": <><h2>International women’s size conversion</h2><p>This guide is a starting point. Fit varies by brand, fabric and silhouette, so use the garment measurements on each product page for the best result.</p><div className="size-table" role="table" aria-label="International women's size conversion"><div role="row"><strong>US / CA</strong><strong>UK / AU / NZ</strong><strong>Bust</strong><strong>Waist</strong><strong>Hip</strong></div>{[["2","6","33 in / 84 cm","25 in / 64 cm","35 in / 89 cm"],["4","8","34 in / 86 cm","26 in / 66 cm","36 in / 91 cm"],["6","10","35 in / 89 cm","27 in / 69 cm","37 in / 94 cm"],["8","12","36 in / 91 cm","28 in / 71 cm","38 in / 97 cm"],["10","14","37.5 in / 95 cm","29.5 in / 75 cm","39.5 in / 100 cm"],["12","16","39 in / 99 cm","31 in / 79 cm","41 in / 104 cm"]].map((row) => <div role="row" key={row[0]}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div><h2>How to measure</h2><ul><li><strong>Bust:</strong> Measure around the fullest part, keeping the tape level.</li><li><strong>Waist:</strong> Measure around your natural waist without pulling tight.</li><li><strong>Hip:</strong> Measure around the fullest part of your hips and seat.</li></ul><p>Between sizes? Contact us with the product name and your measurements for personal fit guidance.</p></>,
  "track-order": <div className="two-column-info"><div><h2>Where is my order?</h2><p>Once your order ships, you’ll receive a dispatch email with carrier tracking. Enter the order details exactly as they appear in your confirmation.</p><p>For help, email <a href="mailto:info@ambboutique.online">info@ambboutique.online</a>.</p></div><TrackOrderForm/></div>,
  account: <div className="two-column-info"><div><h2>Welcome back.</h2><p>Customer accounts are optional. You may shop as a guest; account features can be used when available for order history, saved addresses, returns and preferences.</p><p>New to AMB? You can continue as a guest and use the email address from your order for support and tracking.</p></div><AccountForm/></div>,
};
