import type { Product } from "./data";

// Generated from supplemental-products.csv. Supplier-facing identifiers are never rendered.
export const generatedSupplementalProducts: Product[] = [
  {
    slug: "alba-mini-backpack",
    name: "Alba Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 64,
    badge: "New",
    sheet: "one",
    quadrant: 1,
    colors: ["#e7c5a8"],
    colorNames: ["Apricot"],
    sizes: ["One Size"],
    description: "Compact, polished and ready to move. The Alba Mini Backpack pairs a softly rounded profile with a secure zip closure, a front zip pocket and adjustable hands-free straps. The wide-opening interior keeps daily essentials easy to see, with a slip pocket for smaller pieces.",
    materials: "Smooth PU leather with a durable woven lining and gold-tone metal hardware.",
    care: "Wipe clean with a soft, lightly damp cloth. Store filled and upright in a cool, dry place. Avoid prolonged contact with water, oils and dark denim.",
    images: ["/products/alba-mini-backpack/gallery.svg"],
    gallerySprite: true,
    stock: 123,
    weightOz: 4,
    unitCostUsd: 10.78,
    minimumMarginPercent: 45,
  },
  {
    slug: "rosalie-mini-backpack",
    name: "Rosalie Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 64,
    badge: "New",
    sheet: "one",
    quadrant: 1,
    colors: ["#dba7a7"],
    colorNames: ["Blush Pink"],
    sizes: ["One Size"],
    description: "A soft blush finish brings a feminine note to this compact everyday companion. The Rosalie Mini Backpack features a rounded zip silhouette, a front pocket and adjustable straps, plus a wide-opening interior with a practical slip pocket for the pieces you reach for most.",
    materials: "Smooth PU leather with a durable woven lining and gold-tone metal hardware.",
    care: "Wipe clean with a soft, lightly damp cloth. Store filled and upright in a cool, dry place. Avoid prolonged contact with water, oils and dark denim.",
    images: ["/products/rosalie-mini-backpack/gallery.svg"],
    gallerySprite: true,
    stock: 145,
    weightOz: 4,
    unitCostUsd: 10.78,
    minimumMarginPercent: 45,
  },
  {
    slug: "marlow-mini-backpack",
    name: "Marlow Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 64,
    badge: "New",
    sheet: "one",
    quadrant: 1,
    colors: ["#49352b"],
    colorNames: ["Dark Brown"],
    sizes: ["One Size"],
    description: "Deep brown and quietly refined, the Marlow Mini Backpack keeps everyday organization effortless. Its rounded shape, front zip pocket and adjustable straps balance polish with practicality, while the wide-opening interior reveals a streamlined main compartment and slip pocket.",
    materials: "Smooth PU leather with a durable woven lining and gold-tone metal hardware.",
    care: "Wipe clean with a soft, lightly damp cloth. Store filled and upright in a cool, dry place. Avoid prolonged contact with water, oils and dark denim.",
    images: ["/products/marlow-mini-backpack/gallery.svg"],
    gallerySprite: true,
    stock: 242,
    weightOz: 4,
    unitCostUsd: 9.11,
    minimumMarginPercent: 45,
  },
  {
    slug: "noa-mini-backpack",
    name: "Noa Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 64,
    badge: "New",
    sheet: "one",
    quadrant: 1,
    colors: ["#171717"],
    colorNames: ["Black"],
    sizes: ["One Size"],
    description: "The Noa Mini Backpack is the sleek black essential that goes everywhere. A rounded zip silhouette, compact front pocket and adjustable straps keep the look clean, while the wide-opening interior makes everyday essentials easy to organize and reach.",
    materials: "Smooth PU leather with a durable woven lining and gold-tone metal hardware.",
    care: "Wipe clean with a soft, lightly damp cloth. Store filled and upright in a cool, dry place. Avoid prolonged contact with water, oils and dark denim.",
    images: ["/products/noa-mini-backpack/gallery.svg"],
    gallerySprite: true,
    stock: 113,
    weightOz: 4,
    unitCostUsd: 10.84,
    minimumMarginPercent: 45,
  },
];
