import type { Product } from "./data";

const BAG_CARE = "Wipe clean with a soft damp cloth. Avoid prolonged moisture, direct heat and abrasive surfaces. Store filled to preserve shape.";
const BAG_MATERIALS = "Soft PU vegan leather with synthetic lining and polished metal hardware.";
const BAG_DESCRIPTION = "A petite vegan-leather backpack with a polished flap, front zip pocket and everyday capacity, curated for hands-free city days in San Diego.";
const gallerySprite = { columns: 2, rows: 2, viewWidth: 512, viewHeight: 512 };

export const supplementalProducts: Product[] = [
  {
    slug: "alba-mini-backpack",
    name: "Alba Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 79,
    badge: "New",
    sheet: "one",
    quadrant: 1,
    colors: ["#f5f1e8"],
    colorNames: ["White"],
    sizes: ["One Size"],
    description: BAG_DESCRIPTION,
    materials: BAG_MATERIALS,
    care: BAG_CARE,
    images: ["/products/alba-mini-backpack/gallery.svg?v=20260810-1"],
    gallerySprite,
    stock: 2754,
    weightOz: 13.23,
    unitCostUsd: 29.13,
    minimumMarginPercent: 40,
    styleEligible: true,
  },
  {
    slug: "rosalie-mini-backpack",
    name: "Rosalie Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 79,
    badge: "New",
    sheet: "two",
    quadrant: 2,
    colors: ["#d9a0ab"],
    colorNames: ["Pink"],
    sizes: ["One Size"],
    description: BAG_DESCRIPTION,
    materials: BAG_MATERIALS,
    care: BAG_CARE,
    images: ["/products/rosalie-mini-backpack/gallery.svg?v=20260810-1"],
    gallerySprite,
    stock: 2794,
    weightOz: 13.23,
    unitCostUsd: 37,
    minimumMarginPercent: 40,
    styleEligible: true,
  },
  {
    slug: "marlow-mini-backpack",
    name: "Marlow Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 79,
    badge: "New",
    sheet: "one",
    quadrant: 3,
    colors: ["#774936"],
    colorNames: ["Brown"],
    sizes: ["One Size"],
    description: BAG_DESCRIPTION,
    materials: BAG_MATERIALS,
    care: BAG_CARE,
    images: ["/products/marlow-mini-backpack/gallery.svg?v=20260810-1"],
    gallerySprite,
    stock: 1099,
    weightOz: 13.23,
    unitCostUsd: 37,
    minimumMarginPercent: 40,
    styleEligible: true,
  },
  {
    slug: "noa-mini-backpack",
    name: "Noa Mini Backpack",
    vendor: "AMB BOUTIQUE",
    category: "Bags",
    price: 79,
    badge: "New",
    sheet: "two",
    quadrant: 4,
    colors: ["#5b4f4a"],
    colorNames: ["Gray"],
    sizes: ["One Size"],
    description: BAG_DESCRIPTION,
    materials: BAG_MATERIALS,
    care: BAG_CARE,
    images: ["/products/noa-mini-backpack/gallery.svg?v=20260810-1"],
    gallerySprite,
    stock: 1120,
    weightOz: 13.23,
    unitCostUsd: 37,
    minimumMarginPercent: 40,
    styleEligible: true,
  },
];
