import type { Product } from "./data";

// Heels imported from verified AMB catalogue exports.
// Customer-facing records intentionally contain no marketplace URLs or supplier identifiers.
export const shoeProducts: Product[] = [
  {
    "slug": "solene-woven-slingback",
    "name": "Solene Woven Slingback",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 118,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#eee7d8"],
    "colorNames": ["Cream Ivory"],
    "sizes": ["35","36","37","38","39","40","41","42"],
    "description": "A woven pointed-toe slingback heel with an airy openwork upper and a slim, feminine profile. Designed to bring texture to occasion looks, summer tailoring and evening dresses.",
    "materials": "Woven textile upper with a smooth synthetic lining and sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-01?view=1","/api/catalog-images/shoes/shoe-01?view=2","/api/catalog-images/shoes/shoe-01?view=3","/api/catalog-images/shoes/shoe-01?view=4"],
    "stock": 1334,
    "weightOz": 19.4,
    "unitCostUsd": 36.7,
    "minimumMarginPercent": 40,
    "styleEligible": false
  },
  {
    "slug": "valentina-crystal-sandal",
    "name": "Valentina Crystal Sandal",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["35","36","37","38","39","40","41","42","43","44","45"],
    "description": "A crystal-trim block-heel sandal with a slender crossover strap and secure ankle fastening. The stable heel balances sparkle with wearability for parties, dinners and occasion dressing.",
    "materials": "Textile and synthetic upper with crystal-look embellishment and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-02?view=1","/api/catalog-images/shoes/shoe-02?view=2","/api/catalog-images/shoes/shoe-02?view=3","/api/catalog-images/shoes/shoe-02?view=4"],
    "stock": 437,
    "weightOz": 16.51,
    "unitCostUsd": 21.03,
    "minimumMarginPercent": 40,
    "styleEligible": false
  },
  {
    "slug": "luna-crystal-sandal",
    "name": "Luna Crystal Sandal",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#d8c3a8"],
    "colorNames": ["Beige"],
    "sizes": ["35","36","37","38","39","40","41","42","43","44","45"],
    "description": "A crystal-trim block-heel sandal with a slender crossover strap and secure ankle fastening. The stable heel balances sparkle with wearability for parties, dinners and occasion dressing.",
    "materials": "Textile and synthetic upper with crystal-look embellishment and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-03?view=1","/api/catalog-images/shoes/shoe-03?view=2","/api/catalog-images/shoes/shoe-03?view=3","/api/catalog-images/shoes/shoe-03?view=4"],
    "stock": 437,
    "weightOz": 16.51,
    "unitCostUsd": 21.57,
    "minimumMarginPercent": 40,
    "styleEligible": false
  },
  {
    "slug": "noir-crystal-sandal",
    "name": "Noir Crystal Sandal",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["35","36","37","38","39","40","41","42","43","44","45"],
    "description": "A crystal-trim block-heel sandal with a slender crossover strap and secure ankle fastening. The stable heel balances sparkle with wearability for parties, dinners and occasion dressing.",
    "materials": "Textile and synthetic upper with crystal-look embellishment and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-04?view=1","/api/catalog-images/shoes/shoe-04?view=2","/api/catalog-images/shoes/shoe-04?view=3","/api/catalog-images/shoes/shoe-04?view=4"],
    "stock": 425,
    "weightOz": 16.51,
    "unitCostUsd": 21.44,
    "minimumMarginPercent": 40,
    "styleEligible": false
  },
  {
    "slug": "elodie-crystal-slingback",
    "name": "Elodie Crystal Slingback",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 128,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#d8c3a8"],
    "colorNames": ["Champagne"],
    "sizes": ["36","37","38","39","40","41","42"],
    "description": "A pointed-toe slingback heel finished with all-over crystal-look embellishment for a luminous evening profile. A refined choice for weddings, celebrations and polished occasion dressing.",
    "materials": "Embellished textile upper with a smooth synthetic lining and sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-05?view=1","/api/catalog-images/shoes/shoe-05?view=2","/api/catalog-images/shoes/shoe-05?view=3","/api/catalog-images/shoes/shoe-05?view=4"],
    "stock": 130,
    "weightOz": 17.64,
    "unitCostUsd": 43.07,
    "minimumMarginPercent": 40,
    "styleEligible": false
  },
  {
    "slug": "monaco-buckle-slingback",
    "name": "Monaco Buckle Slingback",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 148,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["36","37","38","39","40"],
    "description": "A sharp pointed-toe slingback set on a 9 cm stiletto heel and finished with a sculptural buckle detail. Built for dressier moments with a sleek, high-impact silhouette.",
    "materials": "Smooth synthetic upper with decorative hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-06?view=1","/api/catalog-images/shoes/shoe-06?view=2","/api/catalog-images/shoes/shoe-06?view=3","/api/catalog-images/shoes/shoe-06?view=4"],
    "stock": 19,
    "weightOz": 21.27,
    "unitCostUsd": 50.44,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "bianca-buckle-slingback",
    "name": "Bianca Buckle Slingback",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 148,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#f4f2ec"],
    "colorNames": ["White"],
    "sizes": ["36","37","38","39","40"],
    "description": "A sharp pointed-toe slingback set on a 9 cm stiletto heel and finished with a sculptural buckle detail. Built for dressier moments with a sleek, high-impact silhouette.",
    "materials": "Smooth synthetic upper with decorative hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-07?view=1","/api/catalog-images/shoes/shoe-07?view=2","/api/catalog-images/shoes/shoe-07?view=3","/api/catalog-images/shoes/shoe-07?view=4"],
    "stock": 25,
    "weightOz": 21.27,
    "unitCostUsd": 50.47,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "celeste-buckle-slingback",
    "name": "Celeste Buckle Slingback",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 148,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#d8c3a8"],
    "colorNames": ["Champagne"],
    "sizes": ["36","37","38","39","40"],
    "description": "A sharp pointed-toe slingback set on a 9 cm stiletto heel and finished with a sculptural buckle detail. Built for dressier moments with a sleek, high-impact silhouette.",
    "materials": "Smooth synthetic upper with decorative hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-08?view=1","/api/catalog-images/shoes/shoe-08?view=2","/api/catalog-images/shoes/shoe-08?view=3","/api/catalog-images/shoes/shoe-08?view=4"],
    "stock": 35,
    "weightOz": 21.27,
    "unitCostUsd": 50.52,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "mosaic-buckle-pump",
    "name": "Mosaic Buckle Pump",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 168,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#b28c78"],
    "colorNames": ["Assorted"],
    "sizes": ["36","37","38","39","40"],
    "description": "A pointed 9 cm pump with a refined metal buckle accent and a slim stiletto heel. The clean court-shoe line works from tailored evening looks to statement occasion dressing.",
    "materials": "Smooth synthetic upper with metal-look hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-09?view=1","/api/catalog-images/shoes/shoe-09?view=2","/api/catalog-images/shoes/shoe-09?view=3","/api/catalog-images/shoes/shoe-09?view=4"],
    "stock": 5,
    "weightOz": 23.17,
    "unitCostUsd": 60.77,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "sable-buckle-pump",
    "name": "Sable Buckle Pump",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 168,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#d8c3a8"],
    "colorNames": ["Beige"],
    "sizes": ["36","37","38","39","40"],
    "description": "A pointed 9 cm pump with a refined metal buckle accent and a slim stiletto heel. The clean court-shoe line works from tailored evening looks to statement occasion dressing.",
    "materials": "Smooth synthetic upper with metal-look hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-10?view=1","/api/catalog-images/shoes/shoe-10?view=2","/api/catalog-images/shoes/shoe-10?view=3","/api/catalog-images/shoes/shoe-10?view=4"],
    "stock": 24,
    "weightOz": 23.17,
    "unitCostUsd": 58.59,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "onyx-buckle-pump",
    "name": "Onyx Buckle Pump",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 168,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["36","37","38","39"],
    "description": "A pointed 9 cm pump with a refined metal buckle accent and a slim stiletto heel. The clean court-shoe line works from tailored evening looks to statement occasion dressing.",
    "materials": "Smooth synthetic upper with metal-look hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-11?view=1","/api/catalog-images/shoes/shoe-11?view=2","/api/catalog-images/shoes/shoe-11?view=3","/api/catalog-images/shoes/shoe-11?view=4"],
    "stock": 13,
    "weightOz": 23.17,
    "unitCostUsd": 57.32,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "rouge-buckle-pump",
    "name": "Rouge Buckle Pump",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 168,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["36","37","38","39","40"],
    "description": "A pointed 9 cm pump with a refined metal buckle accent and a slim stiletto heel. The clean court-shoe line works from tailored evening looks to statement occasion dressing.",
    "materials": "Smooth synthetic upper with metal-look hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-12?view=1","/api/catalog-images/shoes/shoe-12?view=2","/api/catalog-images/shoes/shoe-12?view=3","/api/catalog-images/shoes/shoe-12?view=4"],
    "stock": 49,
    "weightOz": 23.17,
    "unitCostUsd": 58.7,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "cognac-buckle-pump",
    "name": "Cognac Buckle Pump",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 168,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#8a4f35"],
    "colorNames": ["Cognac"],
    "sizes": ["36","37","39","40"],
    "description": "A pointed 9 cm pump with a refined metal buckle accent and a slim stiletto heel. The clean court-shoe line works from tailored evening looks to statement occasion dressing.",
    "materials": "Smooth synthetic upper with metal-look hardware and a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-13?view=1","/api/catalog-images/shoes/shoe-13?view=2","/api/catalog-images/shoes/shoe-13?view=3","/api/catalog-images/shoes/shoe-13?view=4"],
    "stock": 18,
    "weightOz": 23.17,
    "unitCostUsd": 57.72,
    "minimumMarginPercent": 40,
    "heelHeightCm": 9,
    "styleEligible": false
  },
  {
    "slug": "aurelia-nude-patent-slingback-6-cm",
    "name": "Aurelia Nude Patent Slingback · 6 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#d6b39e"],
    "colorNames": ["Nude"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-14?view=1","/api/catalog-images/shoes/shoe-14?view=2","/api/catalog-images/shoes/shoe-14?view=3","/api/catalog-images/shoes/shoe-14?view=4"],
    "stock": 1070,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 6,
    "styleEligible": false
  },
  {
    "slug": "rouge-patent-slingback-6-cm",
    "name": "Rouge Patent Slingback · 6 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-15?view=1","/api/catalog-images/shoes/shoe-15?view=2","/api/catalog-images/shoes/shoe-15?view=3","/api/catalog-images/shoes/shoe-15?view=4"],
    "stock": 1087,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 6,
    "styleEligible": false
  },
  {
    "slug": "onyx-patent-slingback-12-cm",
    "name": "Onyx Patent Slingback · 12 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-16?view=1","/api/catalog-images/shoes/shoe-16?view=2","/api/catalog-images/shoes/shoe-16?view=3","/api/catalog-images/shoes/shoe-16?view=4"],
    "stock": 1383,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 12,
    "styleEligible": false
  },
  {
    "slug": "aurelia-nude-patent-slingback-12-cm",
    "name": "Aurelia Nude Patent Slingback · 12 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#d6b39e"],
    "colorNames": ["Nude"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-14?view=1","/api/catalog-images/shoes/shoe-14?view=2","/api/catalog-images/shoes/shoe-14?view=3","/api/catalog-images/shoes/shoe-14?view=4"],
    "stock": 1370,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 12,
    "styleEligible": false
  },
  {
    "slug": "onyx-patent-slingback-10-cm",
    "name": "Onyx Patent Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-16?view=1","/api/catalog-images/shoes/shoe-16?view=2","/api/catalog-images/shoes/shoe-16?view=3","/api/catalog-images/shoes/shoe-16?view=4"],
    "stock": 1378,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "aurelia-nude-patent-slingback-10-cm",
    "name": "Aurelia Nude Patent Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#d6b39e"],
    "colorNames": ["Nude"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-14?view=1","/api/catalog-images/shoes/shoe-14?view=2","/api/catalog-images/shoes/shoe-14?view=3","/api/catalog-images/shoes/shoe-14?view=4"],
    "stock": 1354,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "rouge-patent-slingback-10-cm",
    "name": "Rouge Patent Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-15?view=1","/api/catalog-images/shoes/shoe-15?view=2","/api/catalog-images/shoes/shoe-15?view=3","/api/catalog-images/shoes/shoe-15?view=4"],
    "stock": 1384,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "rouge-patent-slingback-12-cm",
    "name": "Rouge Patent Slingback · 12 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-15?view=1","/api/catalog-images/shoes/shoe-15?view=2","/api/catalog-images/shoes/shoe-15?view=3","/api/catalog-images/shoes/shoe-15?view=4"],
    "stock": 1383,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 12,
    "styleEligible": false
  },
  {
    "slug": "rouge-patent-slingback-8-cm",
    "name": "Rouge Patent Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-15?view=1","/api/catalog-images/shoes/shoe-15?view=2","/api/catalog-images/shoes/shoe-15?view=3","/api/catalog-images/shoes/shoe-15?view=4"],
    "stock": 1383,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "onyx-patent-slingback-6-cm",
    "name": "Onyx Patent Slingback · 6 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-16?view=1","/api/catalog-images/shoes/shoe-16?view=2","/api/catalog-images/shoes/shoe-16?view=3","/api/catalog-images/shoes/shoe-16?view=4"],
    "stock": 1077,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 6,
    "styleEligible": false
  },
  {
    "slug": "onyx-patent-slingback-8-cm",
    "name": "Onyx Patent Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-16?view=1","/api/catalog-images/shoes/shoe-16?view=2","/api/catalog-images/shoes/shoe-16?view=3","/api/catalog-images/shoes/shoe-16?view=4"],
    "stock": 1367,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "aurelia-nude-patent-slingback-8-cm",
    "name": "Aurelia Nude Patent Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 158,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#d6b39e"],
    "colorNames": ["Nude"],
    "sizes": ["33","34","35","36","37","38","39","40","41","42","43","44","45","46"],
    "description": "A sharply pointed patent-look slingback with a fine heel and clean, elongated line. Available in multiple heel heights so the same polished silhouette can move from day-to-evening dressing to high-impact nights.",
    "materials": "Gloss-finish synthetic upper with a smooth lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-14?view=1","/api/catalog-images/shoes/shoe-14?view=2","/api/catalog-images/shoes/shoe-14?view=3","/api/catalog-images/shoes/shoe-14?view=4"],
    "stock": 1337,
    "weightOz": 17.64,
    "unitCostUsd": 49.41,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "luna-gloss-slingback-10-cm",
    "name": "Luna Gloss Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#d6b39e"],
    "colorNames": ["Nude Gloss"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-17?view=1","/api/catalog-images/shoes/shoe-17?view=2","/api/catalog-images/shoes/shoe-17?view=3","/api/catalog-images/shoes/shoe-17?view=4"],
    "stock": 7054,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "luna-gloss-slingback-8-cm",
    "name": "Luna Gloss Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#d6b39e"],
    "colorNames": ["Nude Gloss"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-18?view=1","/api/catalog-images/shoes/shoe-18?view=2","/api/catalog-images/shoes/shoe-18?view=3","/api/catalog-images/shoes/shoe-18?view=4"],
    "stock": 7054,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "pearl-gloss-slingback-10-cm",
    "name": "Pearl Gloss Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#bdb8b3"],
    "colorNames": ["Pearl Grey"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-19?view=1","/api/catalog-images/shoes/shoe-19?view=2","/api/catalog-images/shoes/shoe-19?view=3","/api/catalog-images/shoes/shoe-19?view=4"],
    "stock": 7055,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "pearl-gloss-slingback-8-cm",
    "name": "Pearl Gloss Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#bdb8b3"],
    "colorNames": ["Pearl Grey"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-20?view=1","/api/catalog-images/shoes/shoe-20?view=2","/api/catalog-images/shoes/shoe-20?view=3","/api/catalog-images/shoes/shoe-20?view=4"],
    "stock": 7056,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "noir-matte-slingback-10-cm",
    "name": "Noir Matte Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#171717"],
    "colorNames": ["Black Matte"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-21?view=1","/api/catalog-images/shoes/shoe-21?view=2","/api/catalog-images/shoes/shoe-21?view=3","/api/catalog-images/shoes/shoe-21?view=4"],
    "stock": 7055,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "noir-matte-slingback-8-cm",
    "name": "Noir Matte Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#171717"],
    "colorNames": ["Black Matte"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-22?view=1","/api/catalog-images/shoes/shoe-22?view=2","/api/catalog-images/shoes/shoe-22?view=3","/api/catalog-images/shoes/shoe-22?view=4"],
    "stock": 7050,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "noir-gloss-slingback-10-cm",
    "name": "Noir Gloss Slingback · 10 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#111111"],
    "colorNames": ["Black Gloss"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-23?view=1","/api/catalog-images/shoes/shoe-23?view=2","/api/catalog-images/shoes/shoe-23?view=3","/api/catalog-images/shoes/shoe-23?view=4"],
    "stock": 7056,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10,
    "styleEligible": false
  },
  {
    "slug": "noir-gloss-slingback-8-cm",
    "name": "Noir Gloss Slingback · 8 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 228,
    "badge": "New",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#111111"],
    "colorNames": ["Black Gloss"],
    "sizes": ["34","35","36","37","38","39","40","41"],
    "description": "A sharply pointed slingback heel with a slim stiletto profile and contrast red outsole. Gloss and matte finishes create distinct evening options while preserving the same clean, elongated silhouette.",
    "materials": "Smooth or gloss-finish synthetic upper with a synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-23?view=1","/api/catalog-images/shoes/shoe-23?view=2","/api/catalog-images/shoes/shoe-23?view=3","/api/catalog-images/shoes/shoe-23?view=4"],
    "stock": 7052,
    "weightOz": 17.64,
    "unitCostUsd": 81.34,
    "minimumMarginPercent": 40,
    "heelHeightCm": 8,
    "styleEligible": false
  },
  {
    "slug": "soleil-bow-stiletto-7-5-cm",
    "name": "Soleil Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#e5c75d"],
    "colorNames": ["Yellow"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-24?view=1","/api/catalog-images/shoes/shoe-24?view=2","/api/catalog-images/shoes/shoe-24?view=3","/api/catalog-images/shoes/shoe-24?view=4"],
    "stock": 6209,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "bianca-bow-stiletto-7-5-cm",
    "name": "Bianca Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#f4f2ec"],
    "colorNames": ["White"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-25?view=1","/api/catalog-images/shoes/shoe-25?view=2","/api/catalog-images/shoes/shoe-25?view=3","/api/catalog-images/shoes/shoe-25?view=4"],
    "stock": 6204,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "rosso-bow-stiletto-7-5-cm",
    "name": "Rosso Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-26?view=1","/api/catalog-images/shoes/shoe-26?view=2","/api/catalog-images/shoes/shoe-26?view=3","/api/catalog-images/shoes/shoe-26?view=4"],
    "stock": 6214,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "rosalie-bow-stiletto-7-5-cm",
    "name": "Rosalie Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#e5a0b8"],
    "colorNames": ["Pink"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-27?view=1","/api/catalog-images/shoes/shoe-27?view=2","/api/catalog-images/shoes/shoe-27?view=3","/api/catalog-images/shoes/shoe-27?view=4"],
    "stock": 6212,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "silver-bow-stiletto-7-5-cm",
    "name": "Silver Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#9fa2a4"],
    "colorNames": ["Grey"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-28?view=1","/api/catalog-images/shoes/shoe-28?view=2","/api/catalog-images/shoes/shoe-28?view=3","/api/catalog-images/shoes/shoe-28?view=4"],
    "stock": 6204,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "celeste-bow-stiletto-7-5-cm",
    "name": "Celeste Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#8fb5c8"],
    "colorNames": ["Blue"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-29?view=1","/api/catalog-images/shoes/shoe-29?view=2","/api/catalog-images/shoes/shoe-29?view=3","/api/catalog-images/shoes/shoe-29?view=4"],
    "stock": 6211,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "noir-bow-stiletto-7-5-cm",
    "name": "Noir Bow Stiletto · 7.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-30?view=1","/api/catalog-images/shoes/shoe-30?view=2","/api/catalog-images/shoes/shoe-30?view=3","/api/catalog-images/shoes/shoe-30?view=4"],
    "stock": 6209,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 7.5,
    "styleEligible": false
  },
  {
    "slug": "noir-bow-stiletto-10-5-cm",
    "name": "Noir Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#171717"],
    "colorNames": ["Black"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-31?view=1","/api/catalog-images/shoes/shoe-31?view=2","/api/catalog-images/shoes/shoe-31?view=3","/api/catalog-images/shoes/shoe-31?view=4"],
    "stock": 6170,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  },
  {
    "slug": "rosso-bow-stiletto-10-5-cm",
    "name": "Rosso Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#b32635"],
    "colorNames": ["Red"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-32?view=1","/api/catalog-images/shoes/shoe-32?view=2","/api/catalog-images/shoes/shoe-32?view=3","/api/catalog-images/shoes/shoe-32?view=4"],
    "stock": 6183,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  },
  {
    "slug": "rosalie-bow-stiletto-10-5-cm",
    "name": "Rosalie Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#e5a0b8"],
    "colorNames": ["Pink"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-33?view=1","/api/catalog-images/shoes/shoe-33?view=2","/api/catalog-images/shoes/shoe-33?view=3","/api/catalog-images/shoes/shoe-33?view=4"],
    "stock": 6126,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  },
  {
    "slug": "bianca-bow-stiletto-10-5-cm",
    "name": "Bianca Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 4,
    "colors": ["#f4f2ec"],
    "colorNames": ["White"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-34?view=1","/api/catalog-images/shoes/shoe-34?view=2","/api/catalog-images/shoes/shoe-34?view=3","/api/catalog-images/shoes/shoe-34?view=4"],
    "stock": 6151,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  },
  {
    "slug": "celeste-bow-stiletto-10-5-cm",
    "name": "Celeste Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 1,
    "colors": ["#8fb5c8"],
    "colorNames": ["Blue"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-35?view=1","/api/catalog-images/shoes/shoe-35?view=2","/api/catalog-images/shoes/shoe-35?view=3","/api/catalog-images/shoes/shoe-35?view=4"],
    "stock": 6150,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  },
  {
    "slug": "silver-bow-stiletto-10-5-cm",
    "name": "Silver Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "two",
    "quadrant": 2,
    "colors": ["#9fa2a4"],
    "colorNames": ["Grey"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-36?view=1","/api/catalog-images/shoes/shoe-36?view=2","/api/catalog-images/shoes/shoe-36?view=3","/api/catalog-images/shoes/shoe-36?view=4"],
    "stock": 6180,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  },
  {
    "slug": "soleil-bow-stiletto-10-5-cm",
    "name": "Soleil Bow Stiletto · 10.5 cm",
    "vendor": "AMB BOUTIQUE",
    "category": "Shoes",
    "subcategory": "Heels",
    "price": 98,
    "badge": "Just In",
    "sheet": "one",
    "quadrant": 3,
    "colors": ["#e5c75d"],
    "colorNames": ["Yellow"],
    "sizes": ["34","35","36","37","38","39","40"],
    "description": "A pointed side-cut stiletto finished with a sculptural bow at the toe. Feminine, polished and occasion-ready, with two heel-height options across a broad colour palette.",
    "materials": "Smooth synthetic upper with bow detail, synthetic lining and synthetic sole. Exact composition follows the product label.",
    "care": "Wipe gently with a soft dry cloth after wear. Keep away from prolonged moisture, direct heat and abrasive surfaces. Store filled and protected to preserve shape.",
    "images": ["/api/catalog-images/shoes/shoe-37?view=1","/api/catalog-images/shoes/shoe-37?view=2","/api/catalog-images/shoes/shoe-37?view=3","/api/catalog-images/shoes/shoe-37?view=4"],
    "stock": 6195,
    "weightOz": 21.16,
    "unitCostUsd": 17.65,
    "minimumMarginPercent": 40,
    "heelHeightCm": 10.5,
    "styleEligible": false
  }
];
