export type AmbCampaign = {
  key: string;
  type: "cart-recovery" | "checkout-recovery" | "lifecycle" | "newsletter";
  step?: number;
  name: string;
  market?: "ALL" | "US" | "CA" | "UK" | "AU" | "NZ";
  subjectA: string;
  subjectB?: string;
  preview: string;
  eyebrow: string;
  headline: string;
  body: string;
  ctaLabel: string;
  ctaUrl: string;
  delayHours?: number;
};

export const cartRecoveryCampaigns: AmbCampaign[] = [
  { key:"cart-01", type:"cart-recovery", step:1, delayHours:1, name:"A gentle reminder", subjectA:"Your AMB edit is still waiting", subjectB:"Still thinking it over?", preview:"Your selected pieces are saved for now.", eyebrow:"YOUR PRIVATE EDIT", headline:"The pieces you chose are still on our mind.", body:"We saved your AMB selection so you can return without starting over. Review the fit, styling notes and delivery details whenever you’re ready.", ctaLabel:"Return to your bag", ctaUrl:"/cart" },
  { key:"cart-02", type:"cart-recovery", step:2, delayHours:12, name:"Style value", subjectA:"Three ways to wear your AMB pick", subjectB:"Make every piece work harder", preview:"A little styling inspiration for your selection.", eyebrow:"STYLE NOTE", headline:"One piece. More than one occasion.", body:"The strongest wardrobe additions earn their place. Pair your selection with relaxed tailoring by day, a polished heel after dark, or a structured bag for an effortless finish.", ctaLabel:"Style your selection", ctaUrl:"/cart" },
  { key:"cart-03", type:"cart-recovery", step:3, delayHours:24, name:"Proof and confidence", subjectA:"Why this AMB piece made the edit", subjectB:"Curated for the way you really dress", preview:"Thoughtful fit, versatility and an elevated finish.", eyebrow:"WHY AMB CHOSE IT", headline:"Selected for more than a beautiful first impression.", body:"Every AMB piece is considered for silhouette, styling potential and the confidence it creates when you put it on. Your selection passed that test.", ctaLabel:"See it again", ctaUrl:"/cart" },
  { key:"cart-04", type:"cart-recovery", step:4, delayHours:48, name:"Objection handling", subjectA:"Questions about fit, shipping or returns?", subjectB:"Let us make your decision easier", preview:"Clear answers before you complete your order.", eyebrow:"WE’RE HERE TO HELP", headline:"Confidence should come before checkout.", body:"Use the size guide without leaving the product page, review delivery for your country, or contact our San Diego team. We want the piece to feel right before it arrives.", ctaLabel:"Review your bag", ctaUrl:"/cart" },
  { key:"cart-05", type:"cart-recovery", step:5, delayHours:72, name:"Tasteful final reminder", subjectA:"A final note about your AMB selection", subjectB:"Last call on the edit you created", preview:"We’ll release your saved selection soon.", eyebrow:"FINAL REMINDER", headline:"Your edit won’t stay reserved forever.", body:"This is our final reminder. If the piece still feels like you, complete your order now. If not, no pressure—we’ll be here with new edits from San Diego.", ctaLabel:"Complete my edit", ctaUrl:"/cart" },
];

export const checkoutRecoveryCampaigns: AmbCampaign[] = [
  { key:"checkout-01", type:"checkout-recovery", step:1, delayHours:.5, name:"Checkout assistance", subjectA:"Need a hand completing your AMB order?", subjectB:"Your secure checkout is ready", preview:"Your order details are saved.", eyebrow:"CHECKOUT ASSISTANCE", headline:"You’re one step away.", body:"Your order is still available. Return to secure checkout to confirm delivery and payment details.", ctaLabel:"Resume secure checkout", ctaUrl:"/checkout" },
  { key:"checkout-02", type:"checkout-recovery", step:2, delayHours:4, name:"Payment confidence", subjectA:"A quick note about secure payment", subjectB:"Your AMB payment is protected", preview:"Encrypted checkout and flexible payment options.", eyebrow:"SECURE BY DESIGN", headline:"A smoother way to finish your order.", body:"AMB checkout is encrypted and processed securely by Stripe. If one method didn’t work, another available card or wallet may complete the order.", ctaLabel:"Try checkout again", ctaUrl:"/checkout" },
  { key:"checkout-03", type:"checkout-recovery", step:3, delayHours:18, name:"Item reminder", subjectA:"The AMB pieces in your order", subjectB:"Your considered edit, ready to complete", preview:"Return to the pieces you selected.", eyebrow:"YOUR ORDER EDIT", headline:"Chosen with intention. Ready when you are.", body:"Your selected size, color and style are attached to the order. Complete checkout before availability changes.", ctaLabel:"View my checkout", ctaUrl:"/checkout" },
  { key:"checkout-04", type:"checkout-recovery", step:4, delayHours:36, name:"Human help", subjectA:"Would personal help make checkout easier?", subjectB:"Reply and our San Diego team will help", preview:"Questions about payment, sizing or delivery?", eyebrow:"PERSONAL ASSISTANCE", headline:"Sometimes a real answer is all you need.", body:"If payment, sizing or international delivery stopped you, reply to this email. Our team will help you find the cleanest next step.", ctaLabel:"Return to checkout", ctaUrl:"/checkout" },
  { key:"checkout-05", type:"checkout-recovery", step:5, delayHours:72, name:"Final checkout note", subjectA:"Final reminder: your AMB checkout", subjectB:"Before we close this order session", preview:"One final opportunity to complete your order.", eyebrow:"FINAL CHECKOUT NOTE", headline:"Complete it now—or leave it with confidence.", body:"We’ll close this recovery sequence after today. If your edit still feels right, your secure checkout is ready. If not, there is nothing else you need to do.", ctaLabel:"Complete my order", ctaUrl:"/checkout" },
];

export const lifecycleCampaigns: AmbCampaign[] = [
  { key:"welcome-newsletter", type:"lifecycle", name:"Newsletter welcome", subjectA:"Welcome to the AMB edit", subjectB:"A warm welcome from San Diego", preview:"Thoughtful style notes, private offers and new arrivals.", eyebrow:"WELCOME TO AMB", headline:"Considered style, delivered with warmth.", body:"Thank you for joining AMB BOUTIQUE. Expect useful styling ideas, founder notes from Ana Paula Maciel, early access and carefully chosen offers—never noise for the sake of sending.", ctaLabel:"Explore the boutique", ctaUrl:"/" },
  { key:"welcome-discount", type:"lifecycle", name:"First order offer", subjectA:"Your private AMB welcome code", subjectB:"10% off your first AMB order", preview:"Your first-order code is inside.", eyebrow:"A PRIVATE WELCOME", headline:"A little something for your first AMB edit.", body:"Use code WELCOME10 for 10% off your first eligible full-price order. The best eligible discount applies and offers do not stack.", ctaLabel:"Use my welcome offer", ctaUrl:"/collections/all" },
  { key:"order-confirmed", type:"lifecycle", name:"Order confirmation", subjectA:"Your AMB order is confirmed", preview:"We’re preparing your order in San Diego.", eyebrow:"ORDER CONFIRMED", headline:"Thank you—your AMB order is in motion.", body:"We received your payment and are preparing the selected pieces. You’ll receive the next update when your order moves forward.", ctaLabel:"View order details", ctaUrl:"/account" },
  { key:"payment-recovery", type:"lifecycle", name:"Payment recovery", subjectA:"We couldn’t complete your AMB payment", subjectB:"A quick way to finish your AMB order", preview:"Try another card or payment method.", eyebrow:"PAYMENT UPDATE", headline:"Your order is still possible.", body:"The payment did not complete. Check the billing details, try another card or available wallet, or contact your bank. Your AMB selection has not been charged.", ctaLabel:"Try payment again", ctaUrl:"/checkout" },
];

export const newsletterCampaigns: AmbCampaign[] = [
  ["brand-01","Meet AMB BOUTIQUE","The San Diego point of view behind AMB","A boutique built around polished, wearable confidence.","OUR STORY","Style should feel elevated—and still feel like you.","Meet AMB BOUTIQUE: a women’s edit founded by Ana Paula Maciel in San Diego, shaped by coastal ease and a sharp eye for pieces that work beyond one occasion.","Read our story","/our-story","ALL"],
  ["founder-02","Founder note","A note from Ana Paula","Why every edit begins with real life.","FOUNDER’S NOTE","The best wardrobe starts with how you want to feel.","Ana Paula shares the principle behind AMB: choose fewer pieces with more styling potential, then make the details feel unmistakably yours.","Meet the founder","/our-story","ALL"],
  ["style-03","Three-piece formula","The three-piece formula that always looks polished","An easy styling lesson worth saving.","AMB STYLE SCHOOL","A complete look can be wonderfully simple.","Start with one strong silhouette, add one structured finishing piece, then choose a shoe that changes the mood. That is the AMB three-piece formula.","Shop the formula","/collections/all","ALL"],
  ["dress-04","Dress edit","The dress edit: one decision, a complete look","Dresses chosen for impact without the effort.","THE DRESS EDIT","The easiest answer to “what should I wear?”","Discover silhouettes that move from long lunches to evening plans with only a change of shoes and bag.","Shop dresses","/collections/dresses","ALL"],
  ["tops-05","Tops edit","The tops that make the rest of your wardrobe easier","Build more looks from what you already own.","WARDROBE VALUE","A beautiful top can unlock five outfits.","Meet polished blouses and versatile tops designed to refresh trousers, skirts, denim and tailoring you already love.","Shop tops","/collections/tops","ALL"],
  ["bags-06","Bag edit","The finishing touch your outfit was waiting for","A bag should complete the look, not compete with it.","THE BAG EDIT","Structure, proportion and just enough personality.","Explore AMB bags selected to bring balance to work, weekend and evening outfits.","Shop bags","/collections/bags","ALL"],
  ["heels-07","Heels edit","A better heel changes the whole silhouette","Elegance with a considered step.","THE HEEL EDIT","The quickest way to change the mood of a look.","From slingbacks to pumps, see the AMB heels chosen to sharpen dresses, trousers and skirts.","Shop heels","/collections/heels","ALL"],
  ["fit-08","Fit education","How to choose your AMB size with confidence","A practical guide before you order.","FIT, SIMPLIFIED","Measure once. Choose with confidence.","Use our in-page size guide and fit notes to compare your measurements without losing your place on the product page.","Use the size guide","/size-guide","ALL"],
  ["look-09","How to Style It","How to style it: let the outfit build itself","Real matches from pieces actually available.","HOW TO STYLE IT","A complete look without random recommendations.","AMB only suggests complementary categories—never another dress beside your dress—and only shows pieces currently available.","Build a look","/collections/all","ALL"],
  ["proof-10","Customer confidence","Why women return to a well-made edit","The quiet value of a piece that earns repeat wear.","WHY IT WORKS","Confidence is the best form of social proof.","A strong AMB piece should make getting dressed easier, attract the right kind of compliment and keep returning to your weekly rotation.","Explore best sellers","/collections/best-selling","ALL"],
  ["new-11","New arrivals","Just in: the newest AMB edit","Fresh silhouettes, limited first release.","NEW IN","New pieces, same considered point of view.","See the latest dresses, tops, bags and heels to enter the AMB edit.","Shop new in","/collections/new-in","ALL"],
  ["value-12","Cost per wear","The shopping question that changes everything","Think beyond price and toward repeat wear.","STYLE VALUE","Will you reach for it again next week?","Before buying, imagine three occasions and three pairings. If the piece supports all six, it is likely earning its place.","Shop versatile pieces","/collections/all","ALL"],
  ["work-13","Work edit","The polished work edit—without feeling overdressed","Clean lines for meetings, travel and everything between.","THE WORK EDIT","Professional can still feel personal.","Discover dresses, blouses, bags and heels that create authority without sacrificing ease.","Shop the work edit","/collections/all","ALL"],
  ["weekend-14","Weekend edit","Your elevated weekend, already styled","Relaxed pieces with a polished finish.","WEEKEND, REFINED","Ease looks better with intention.","Build a weekend outfit around breathable silhouettes, a practical bag and one refined detail.","Shop weekend style","/collections/all","ALL"],
  ["evening-15","Evening edit","After dark, keep the silhouette simple","An AMB guide to evening polish.","EVENING EDIT","Let one detail do the talking.","Choose a clean dress, a confident heel and a bag with just enough shine. Restraint makes the look feel expensive.","Shop evening style","/collections/all","ALL"],
  ["spring-us-16","US spring","The San Diego spring edit","Lighter layers and new-season color.","SPRING IN SAN DIEGO","A fresh start for the pieces you wear most.","Ease into warmer days with polished dresses, breathable tops and lighter accessories.","Shop the spring edit","/collections/new-in","US"],
  ["summer-us-17","US summer","Summer, styled the AMB way","Heat-ready silhouettes with a polished finish.","SUMMER EDIT","Light on effort. Strong on style.","Discover breathable dresses, tops and accessories selected for long warm days and spontaneous evening plans.","Shop summer","/collections/all","US"],
  ["fall-us-18","US fall","The first look at fall","Texture, richer color and considered layers.","FALL EDIT","A change of season, not a change of self.","Transition your wardrobe with deeper tones, structured bags and pieces that layer without bulk.","Shop fall","/collections/new-in","US"],
  ["holiday-us-19","US holiday","A polished holiday edit","Pieces for dinners, celebrations and thoughtful gifting.","HOLIDAY EDIT","Dress for the memory, not only the photo.","Choose occasion pieces with enough versatility to keep wearing after the celebration.","Shop holiday style","/collections/all","US"],
  ["canada-20","Canada edit","The AMB Canada edit","Polished layers and occasion-ready details.","CURATED FOR CANADA","Style that moves easily between seasons.","Explore versatile pieces with clear pricing in Canadian dollars and delivery options selected for Canada.","Shop the Canada edit","/collections/all","CA"],
  ["canada-day-21","Canada Day","A red-and-white edit for Canada Day","A subtle way to dress for the moment.","CANADA DAY EDIT","Celebrate in color you’ll wear again.","Discover red, white and neutral pieces that feel festive without becoming costume.","Explore the edit","/collections/all","CA"],
  ["uk-22","UK edit","The AMB edit for the UK","Layer-friendly silhouettes and polished finishing pieces.","CURATED FOR THE UK","Ready for plans—and a change in weather.","Build adaptable looks with dresses, refined tops, a structured bag and the right heel.","Shop in GBP","/collections/all","UK"],
  ["uk-bank-23","UK bank holiday","What to wear for the long weekend","One effortless edit for every plan.","BANK HOLIDAY STYLE","From brunch to dinner without a full outfit change.","Choose pieces that travel through a full day: relaxed first, polished when the accessories change.","Shop the long-weekend edit","/collections/all","UK"],
  ["australia-24","Australia edit","The AMB Australia edit","Warm-weather polish in Australian dollars.","CURATED FOR AUSTRALIA","An elevated answer to warmer days.","Discover breathable silhouettes and confident accessories selected for the Australian season.","Shop in AUD","/collections/all","AU"],
  ["australia-day-25","Australia Day","An easy Australia Day edit","Relaxed, polished and ready for summer plans.","SUMMER CELEBRATION","Keep the color easy and the silhouette strong.","Explore light dresses, tops and practical bags for an effortless day-to-evening look.","Explore the edit","/collections/all","AU"],
  ["new-zealand-26","New Zealand edit","The AMB New Zealand edit","Versatile layers and clean silhouettes in NZD.","CURATED FOR NEW ZEALAND","Style that adapts beautifully.","Build outfits around pieces that move between changing weather, work and weekend plans.","Shop in NZD","/collections/all","NZ"],
  ["matariki-27","Matariki","A thoughtful midwinter edit for Matariki","Warm layers and pieces chosen to gather in.","MATARIKI EDIT","A season for reflection, connection and warmth.","Explore an understated edit for shared meals, winter plans and meaningful moments.","Explore the edit","/collections/all","NZ"],
  ["gift-28","Gift guide","The AMB gift guide for women with a point of view","Thoughtful pieces without the guesswork.","THE GIFT EDIT","Give her something that feels chosen.","Bags and versatile accessories make beautiful gifts when size is uncertain; dresses and tops become personal when you know her silhouette.","Shop gifts","/collections/all","ALL"],
  ["private-29","Private access","Private access: an early look at what’s next","Subscribers see the edit first.","EARLY ACCESS","A quieter way to shop new arrivals.","Take an early look before the public release and choose while the full size and color edit is available.","Shop early access","/collections/new-in","ALL"],
  ["community-30","Community content","One AMB piece, three real-life stories","Style ideas worth saving and sharing.","AMB COMMUNITY","Teach first. Inspire next. Shop when it feels right.","See three ways the AMB community makes one polished piece feel completely personal—then save the look that fits your life.","See the styling story","/journal","ALL"],
].map(([key,name,subjectA,preview,eyebrow,headline,body,ctaLabel,ctaUrl,market]) => ({
  key, type:"newsletter" as const, name, subjectA, preview, eyebrow, headline, body,
  ctaLabel, ctaUrl, market: market as AmbCampaign["market"],
}));

export const allCampaigns = [
  ...lifecycleCampaigns,
  ...cartRecoveryCampaigns,
  ...checkoutRecoveryCampaigns,
  ...newsletterCampaigns,
];

export function findCampaign(key: string) {
  return allCampaigns.find((campaign) => campaign.key === key) || lifecycleCampaigns[0];
}

